### ISSUE TITLE
Request for KSP v1.6.1 compability

### ISSUE THREAD

**Issue by getupandgo** [ihsoft/KAS#257]

**Comment by ihsoft** [comment]
The latest KAS version _is_ compatible. The only issue is the complaining dialog, but it only shows up due to the magor KSP version change.

Pelase, unless the real functionality is broken, don't bring up it to my attention since I _am_ well aware about the `KSP 1.6.1` version release. When the time is right, there will be a release of new KAS. I haven't abandoned the mod! Meanwhile, you may simply drop `MiniAVC.dll` from the folder amd live in peace.
