### ISSUE TITLE
KAS 1.4.36908.7097 not working in KSP 1.8.0.2686

### ISSUE THREAD

**Issue by krbolson** [ihsoft/KAS#281]
Grab Connector button on RTS right-click menu is present, but does not function, err, grab it.

**Comment by ihsoft** [comment]
I'd surprised if it wasn't broken. It'll take time to have KIS/KAS fixed.

**Comment by ihsoft** [comment]
So, I've finally got an opportunity to get to KAS. And I don't observe the issue. Could you please remove any of the mods from your system , except KAS and its dependants, and retry? I'd really appreciate a video of this test run.

**Comment by MystLeissa** [comment]
I think he's confusing the grab on the RTS with the fact that it attaches to the jetpack (not sure but I haven't had any trouble running KAS on 1.8.0 since removing all my 1.7.3 mods) The Jetpack attachment itself doesn't do much beyond actually providing a tether point on 1.7.3 - I'm not sure what it's actually supposed to do but that wasn't a 1.8.0 issue.

**Comment by krbolson** [comment]
After upgrading module manager and KIS, I do not see the problem occur.  Tried down-grading and was unable to reproduce problem.  I'll try to get better documentation if I see it again.  I will close the issue.
