### ISSUE TITLE
JS-1 Socket right click menu not showing up

### ISSUE THREAD

**Issue by bakadave** [ihsoft/KAS#286]
I recently ran into a bug where the right click menu to attach cable to JS-1 sockets won't show up in certain cases. The issue persists throughout program restarts and detaching/reattaching socket. Here are some scenarios to reproduce:

**scenario 1:**
I accidentally pressed left mouse button instead of X while installing JS1 and it fell ~1m to the ground. When I picked up it installed fine on the the part, but couldn't attach cable any more.

**scenario 2:**
Winch sank through the ground and exploded due to Kraken-related issues. The socket it was connected to was salvaged but could no longer be used.

I looked in the save game file and couldn't find any difference there between working and non-working sockets. Right clicking works well in any other case.

**Comment by ihsoft** [comment]
We need reproducible cases. Can you make two save files on the stock parts only?

Scenario #1 relates to a part destruction, and this case is tricky - there can be edge cases not covered in the code. KAS is designed so that it tracks the parts state, so if there is a mismatch, then there will be errors and warnings in the logs. That said, I need at least the logs. Even better, logs + a save file.

Scenario #2 seems very straightforward. There should be no difference between attaching the part right out of the inventory, or by picking it up from the ground. Without extra data I have no idea what could get wrong there. Save file + logs is the only way to shed the light on the problem.

**Comment by bakadave** [comment]
Thank you for the quick response. I'll try to send you the files by tomorrow.

**Comment by bakadave** [comment]
I made the mistake (or is it) to upgrade to KSP 1.9 and I have been unable to reproduce the bug since. I'll get back to you if it happens again, sorry for wasting your time.

**Comment by ihsoft** [comment]
It seems this issue is not reproducing. Feel free to re-open if it shows up again.
