### ISSUE TITLE
KSP 1.11: Cannot link PCB-1 Portable Cable Bracing 

### ISSUE THREAD

**Issue by EoD** [ihsoft/KAS#305]
I used the MM patch and removed 4x PCB-1 from the ship, added them to a stock inventory and attached them. One of the 4 PCBs did not provide me with the option to "link" (no matter how close I am):
![image](https://user-images.githubusercontent.com/293499/105531375-81380680-5ce9-11eb-872b-1b921f35b84c.png)

I have only 4x PCB-1 in my save and this one of them not show "Linked", so I assume it is this one: 
1. Before using Construction Mode: https://gist.github.com/EoD/4eb4f1b0c1213a4eb21df027f9b202fd#file-before-using-construction-mode
2. After using Construction Mode: https://gist.github.com/EoD/4eb4f1b0c1213a4eb21df027f9b202fd#file-after-using-construction-mode

Here is the KSP.log filtered for "KAS". Unfortunately, it does only mention the other PCBs in there: https://gist.github.com/EoD/9552c27bab8bc1fdf3136f7e26ad0d4d

**Comment by ihsoft** [comment]
KAS is not compatible with the stock cargo system. There was glitches and unexplained behavior found when testing. There is a comment on the forum about it posted on December 26, 2020.

In nutshell, you cannot use the part because stuck in an intermediate state `RejectingLinks`. How exactly it has happen cannot be explained at the moment. As a workaround, use KIS to attach KAS parts in flight. And remove the `ModuleCargoPart` module from the KAS parts to avoid further problems. Do not carry or attach KAS parts using the stock game functionality! As for the existing not working parts, I advise to trash them. Their state may be corrupted beyond repair.

**Comment by EoD** [comment]
@ihsoft I am aware that it is not supported yet, I just wanted to leave the note here. I was able to make it attachable by overwriting the state.
But I don't think any of them actually worked, at least when I messed around with it, they did not seem to do anything (the cable just stretched to infinity).

How do you suggest to trash them? It is part of a long-running station which I don't want to deorbit if I can avoid it.
Is it enough to store them in a stock inventory to "reset" them?

**Comment by ihsoft** [comment]
Thank you a lot for helping debugging it! I've put the note just to ensure you're not using this stuff in your carrier game.

> How do you suggest to trash them?

The easiest way is to enable the debugging mode in `KIS`. This will reveal "Spawn" and "Dispose" options in the inventories. This is how I usually do testing in flight.

> Is it enough to store them in a stock inventory to "reset" them?

Unlikely. The part's state is persisted when the part is stored. It may help in this particular case, but it won't work in general.

**Comment by ihsoft** [comment]
Ref commit 49713071
